{{ if .Values.isMinikube }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 512M
  hostPath:
    path: /var/cloud/mongodata
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv3
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/cloud/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv2
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv4
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videofiles
    type: DirectoryOrCreate
  {{- end }}