{{- if eq .Values.vms.isCloud "false" }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  collection-create
spec:
  completions: 1
  backoffLimit: 3
  parallelism: 1
# ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        job: create-collection
    spec:
      containers:
        - env:
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_ADMIN_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.databaseName }}
          name: collection-create
          image: mongoclient/mongoclient
          command:
          - /bin/sh
          - -c
          - "mongo  {{ .Values.mongodb.serviceName }}:27017/$MONGODB_DATABASE -u $MONGODB_USERNAME -p 
          $MONGODB_PASSWORD --eval=\"db.video.drop()\"&& mongo  {{ .Values.mongodb.serviceName }}:27017/$MONGODB_DATABASE -u $MONGODB_USERNAME -p
          $MONGODB_PASSWORD --eval=\"db.createCollection('video', {capped: true,   size:  {{ .Values.mongodb.videoCollectionSize }},   max: {{ .Values.mongodb.videoCollectionMaxDocs }} })\""
      restartPolicy: OnFailure
{{- end}}
